name: Docker Image CI

on: 
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build docker image
        run: |
             docker login --username=${{ secrets.DOCKER_USN }} --password=${{ secrets.DOCKER_PWD }}
             docker build . --file Dockerfile --tag jiaoguohui/vapor4email:$(date +%s) --tag jiaoguohui/vapor4email:${{ secrets.DOCKER_LATEST }} --build-arg env=docker
             docker push jiaoguohui/vapor4email:${{ secrets.DOCKER_LATEST }}

